### ISSUE TITLE
Erro: "Cartão não suportado"

### ISSUE THREAD

**Issue by pmanu93** [poreid/poreid#5]
Bom dia, 

Ultimamente tem ocorrido o erro "Cartão não suportado" com alguns cartões.
Aparentemente este erro é provocado por uma nova versão dos cartões de cidadão que agora é disponibilizada.

Está prevista alguma correcção para esta situação?

```js
//Erro:
{error: "Cartão não suportado", cause: null, exception: "org.poreid.UnknownCardException"}
```

Cumprimentos,
Pedro Silva

**Comment by DanielNovo** [comment]
Boa tarde,

Cartões com a versão 006.007.23 está a dar erro na leitura: "Cartão não suportado"
Testei cartões com as versões: 005.004.22 e 006.005.22 e está ok.

Obrigado,

Daniel Novo

**Comment by DanielNovo** [comment]
Pedro Silva, se fizer fork ou download dos sources,  gerar um novo poreid jar o problema fica resolvido.

No poreid-1.51.jar, ficheiro poreid.config.xml falta uma entrada para os novos cartões.

<smartcard>
  <atr>3BFF9600008131804380318065B0850300EF120FFF82900067</atr>
    <properties>
      <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
        <cache-enabled>true</cache-enabled>
    </properties>
</smartcard>

**Comment by pmanu93** [comment]
@DanielNovo , Foi o que acabei por fazer. 
Preferia que tivesse sido uma versão oficial.. mas pronto, está resolvido.

Obrigado.
