### ISSUE TITLE
Allow to pass the pin code directly when retrieving the address

### ISSUE THREAD

**Issue by florian-courault** [poreid/poreid#9]
Hello,
As the title says, I'd like to pass the address pin code directly to get the address.
Indeed, I need to fully integrate the reading of Portuguese cards in my software.
I have made a pull request which allow that. #10 
Thank you for your help, and for your very useful project !

**Comment by ruimartinho** [comment]
Hello, what would be the use case? Where would the pin be obtained?

**Comment by florian-courault** [comment]
Hello, my goal is to ask for the PIN code directly in my software, to have my own UI.

**Comment by florian-courault** [comment]
I have made some other changes on my fork. I am going to open an issue for each one, so if you agree with it, you can merge it :)

**Comment by ruimartinho** [comment]
solved.
